name: Run Tests

on:
    push:
    pull_request:
      types: [opened, reopened]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    env:
        RPC_MAINNET: ${{ secrets.RPC_MAINNET }}
        CHAIN_ID: ${{ secrets.CHAIN_ID }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of .t.sol files in src/test
      id: get-file-list
      run: |
        FILES=$(find src/test -type f -name '*.t.sol' | sed 's#src/test/##')
        echo "FILES=$FILES"
        echo "::set-output name=files::$FILES"
      
    - name: Run forge test for each file
      run: |
        for file in ${{ steps.get-file-list.outputs.files }}
        do
          forge test --match-path $file
        done