name: Slither Analysis
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  analyze:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: crytic/slither-action@v0.3.0
        with:
          fail-on: none