name: Run Tests

on: [push, pull_request]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get list of .t.sol files in src/test
      run: |
        FILES=$(find src/test -type f -name '*.t.sol' | sed 's#src/test/##' | jq -R -s -c 'split("\n")[:-1]')
        echo "::set-output name=matrix::$FILES"
      id: set-matrix

  run-tests:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: ${{fromJson(needs.prepare.outputs.matrix)}}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run forge test for the file
      run: forge test --match-path ${{ matrix.file }}
